"""Add artist_title column to User model

Revision ID: 374449697a1b
Revises: 4b4ef4d37304
Create Date: 2024-05-03 04:39:46.125619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374449697a1b'
down_revision = '4b4ef4d37304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('request')
    op.drop_table('submission')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_title', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('artist_description', sa.Text(), nullable=True))
        batch_op.drop_column('total_points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_points', sa.INTEGER(), nullable=True))
        batch_op.drop_column('artist_description')
        batch_op.drop_column('artist_title')

    op.create_table('submission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('request_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('ranking', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('image')
    # ### end Alembic commands ###
