"""change image datatype to BLOB

Revision ID: 56db08611725
Revises: 5fc026af1328
Create Date: 2024-05-14 03:36:14.427663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56db08611725'
down_revision = '5fc026af1328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.TEXT(length=100),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.BLOB(),
               type_=sa.TEXT(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
