"""add Message entity

Revision ID: ba22ce5b6610
Revises: 4b4ef4d37304
Create Date: 2024-05-04 14:46:24.855122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba22ce5b6610'
down_revision = '4b4ef4d37304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_from', sa.Integer(), nullable=True),
    sa.Column('user_to', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.CheckConstraint('user_from != user_to'),
    sa.ForeignKeyConstraint(['user_from'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
