"""add is_read bool to messaages table

Revision ID: ccaf127c197e
Revises: 0d8bd8fa9a7c
Create Date: 2024-05-13 17:49:08.204695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccaf127c197e'
down_revision = '0d8bd8fa9a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
