"""Undid previous

Revision ID: eff57309fbd8
Revises: 705dacb047d3
Create Date: 2024-05-16 10:57:45.519654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff57309fbd8'
down_revision = '705dacb047d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.alter_column('min_price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('max_price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.alter_column('max_price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('min_price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
